[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = "C:\\Users\\Etienne Herzig\\Documents\\coding\\FluixOS\\x86_64-fluix_os.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"